### ISSUE TITLE
constraint.md

### ISSUE THREAD

**Issue by khantm02** [HYF-Class22/agile-development-group2-all-about-trees#4]
- [x] write constraint.md file
  - [x] constraints > internal, external

**Comment by alasaidi** [comment]
exemple
# Constraints

## External

- **Project Deadline:** The website must be completed and launched by [specific date].
- **UI Design and Color Scheme:** The client has provided a predefined UI design and color scheme that must be adhered to.

## Internal: Involuntary

- **Team Skill Levels:** The team members have varying skill levels in web development, which may impact the complexity of features and functionalities that can be implemented.
- **Time Availability:** The team has a limited amount of time available to work on the project due to other commitments and responsibilities.

## Internal: Voluntary

- **Coding Style & Conventions:** The team has decided to follow a specific coding style and set of conventions to ensure consistency and maintainability of the codebase.
- **Code Review Checklist:** A comprehensive code review checklist has been agreed upon to maintain code quality and identify potential issues before merging into the main repository.
- **Work Hours:** The team has established a set number of hours per week dedicated to working on the project.
- **Color Limitation:** The decision has been made to use only black and white colors in the design to create a minimalistic and focused aesthetic.
